force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Car_Owner__c.field-meta.xml
<CustomField>
    <fullName>Car_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car_Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Car_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Showroom__c.field-meta.xml
<CustomField>
    <fullName>Showroom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Showroom</label>
    <referenceTo>Showroom__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Showroom__c.field-meta.xml
<CustomField>
    <fullName>Showroom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Showroom</label>
    <referenceTo>Showroom__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Showroom__c/Showroom__c.object-meta.xml
<CustomObject>
    <label>Showroom</label>
    <nameField>
        <label>Showroom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showrooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CarsLWCController.cls
public with sharing class CarsLWCController {
	@AuraEnabled(cacheable=true)
	public static List<CarWrapper> getAllCars() {
		List<CarWrapper> carWrapperList = new List<CarWrapper>();
		List<Car__c> carList = [
			SELECT Id, Name, Model__c, Color__c, Price__c, Showroom__r.Name, Car_Owner__r.Name
			FROM Car__c
			LIMIT 50
		];
		if (!carList.isEmpty()) {
			for (Car__c car : carList) {
				CarWrapper carsWrapper = new CarWrapper();
				carsWrapper.carId = car.Id;
				carsWrapper.carName = car.Name;
				carsWrapper.carModel = car.Model__c;
				carsWrapper.carColor = car.Color__c;
				carsWrapper.carPrice = car.Price__c;
				carsWrapper.showroomName = car.Showroom__r.Name;
				carsWrapper.carOwnerName = car.Car_Owner__r.Name;

				carWrapperList.add(carsWrapper);
			}
		}
		return carWrapperList;
	}

	@AuraEnabled(cacheable=true)
	public static List<Showroom__c> getShowroom() {
		List<Showroom__c> showroom = [SELECT Id, Name FROM Showroom__c];
		return showroom;
	}

	@AuraEnabled(Cacheable=true)
	public static List<Car__c> getBoats(String carColor, String ShowroomId) {
		// Without an explicit carColor, the full list is desired
		String query =
			'SELECT ' +
			'Id, Name, Model__c, Color__c, Price__c, Showroom__r.Name, Car_Owner__r.Name' +
			'FROM Car__c';
		if (String.isNotBlank(carColor)) {
			query += ' WHERE Color__c = :carColor';
		} if (String.isNotBlank(carColor)) {
			query += ' AND Showroom__r.Name = :ShowroomId';
		}
		query += ' WITH SECURITY_ENFORCED ';
		return Database.query(query);
	}

	public class CarWrapper {
		@AuraEnabled
		public String carId;
		@AuraEnabled
		public String carName;
		@AuraEnabled
		public String carModel;
		@AuraEnabled
		public String carColor;
		@AuraEnabled
		public Decimal carPrice;
		@AuraEnabled
		public String showroomName;
		@AuraEnabled
		public String carOwnerName;
	}
}