force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Car_Owner__c.field-meta.xml
<CustomField>
    <fullName>Car_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car_Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Car_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Showroom__c.field-meta.xml
<CustomField>
    <fullName>Showroom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Showroom</label>
    <referenceTo>Showroom__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Showroom__c.field-meta.xml
<CustomField>
    <fullName>Showroom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Showroom</label>
    <referenceTo>Showroom__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Showroom__c/Showroom__c.object-meta.xml
<CustomObject>
    <label>Showroom</label>
    <nameField>
        <label>Showroom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showrooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HomePageController.cls
public class HomePageController {
	public String colorPickValue { get; set; }
	public String showroomPickValue { get; set; }
	public String recId { get; set; }
	public List<Car__c> getAllCars { get; set; }
	public List<Showroom__c> getAllShowrooms { get; set; }

	public HomePageController() {
		loadData();
	}

	private void loadData() {
		getAllCars = [
			SELECT Id, Name, Model__c, Color__c, Price__c, Showroom__r.Name, Car_Owner__r.Name
			FROM Car__c
			LIMIT 50
		];
	}

	public void getCars() {
		getAllCars = new List<Car__c>(
			[
				SELECT Id, Name, Model__c, Color__c, Price__c, Showroom__r.Name, Car_Owner__r.Name
				FROM Car__c
				WHERE Color__c = :colorPickvalue AND Showroom__r.Name = :showroomPickValue
				LIMIT 50
			]
		);
		System.debug('1>>>>>>>>>>>>>>>>>>>>>>>>>>>' + getAllCars);
	}

	//Filteres goes here:
	public List<SelectOption> getSelectColor() {
		List<SelectOption> optionsColor = new List<SelectOption>();
		Schema.DescribeFieldResult colorField = Car__c.Color__c.getDescribe();
		System.debug('2>>>>>>>>>>>>>>>>>>>>>>>>>>>' + colorField);
		optionsColor.add(new SelectOption('--Select color--', '--Select color--'));
		for (Schema.PicklistEntry picklistEntry : colorField.getPicklistValues()) {
			optionsColor.add(new SelectOption(picklistEntry.getValue(), picklistEntry.getLabel()));
		}
		System.debug('3>>>>>>>>>>>>>>>>>>>>>>>>>>>' + optionsColor);
		return optionsColor;
	}

	public List<SelectOption> getSelectShowroom() {
		List<SelectOption> optionsShowroom = new List<SelectOption>();
		List<Showroom__c> shList = new List<Showroom__c>();
		shList = [SELECT Id, Name FROM Showroom__c];
		optionsShowroom.add(new SelectOption('--Select showroom--', '--Select showroom--'));
		for (Showroom__c showroom : shList) {
			optionsShowroom.add(new SelectOption(showroom.Name, showroom.Name));
		}
		System.debug('66666>>>>>>>>>>>>>>>>>>>>>>>>>>>' + optionsShowroom);
		return optionsShowroom;
	}

	
	public PageReference forwardToSchedule() {
		return new PageReference('/SchedulePage');
	}
}