force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Car_Owner__c.field-meta.xml
<CustomField>
    <fullName>Car_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car_Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Car_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Showroom__c.field-meta.xml
<CustomField>
    <fullName>Showroom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Showroom</label>
    <referenceTo>Showroom__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Showroom__c.field-meta.xml
<CustomField>
    <fullName>Showroom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Showroom</label>
    <referenceTo>Showroom__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/Maintenance__c.object-meta.xml
<CustomObject>
    <label>Maintenance</label>
    <nameField>
        <label>Maintenance</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Maintenances</relationshipLabel>
    <relationshipName>Maintenances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Scheduled_date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_date__c</fullName>
    <label>Scheduled date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Showroom__c.field-meta.xml
<CustomField>
    <fullName>Showroom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Showroom</label>
    <referenceTo>Showroom__c</referenceTo>
    <relationshipLabel>Maintenances</relationshipLabel>
    <relationshipName>Maintenances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Showroom__c/Showroom__c.object-meta.xml
<CustomObject>
    <label>Showroom</label>
    <nameField>
        <label>Showroom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showrooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ScheduleController.cls
public class ScheduleController {
	public Maintenance__c maintenance { get; set; }
	public Date dateVal { get; set; }
	public Id maintId { get; set; }

	public Car__c singleCar { get; set; }

	public ScheduleController() {
		Id id = Apexpages.currentPage().getParameters().get('id');
		singleCar = [
			SELECT
				Id,
				Name,
				Car_Owner__r.Name,
				Color__c,
				Model__c,
				Price__c,
				Showroom__c,
				OwnerId,
				(SELECT Id, Scheduled_date__c FROM Maintenances__r)
			FROM Car__c
			WHERE Id = :id
		];
		System.debug('>>>>>>>>>>>>>>>> Single car:' + singleCar);
	}

	public PageReference forwardToHomePage() {
		return new PageReference('/HomePage');
	}

	// public ScheduleController() {
		//Id carId = Apexpages.currentPage().getParameters().get('id');
		//maintenance = [SELECT Id, Showroom__c, Scheduled_date__c, Car__c FROM Maintenance__c WHERE Car__c = :carId];
	// 	getAllCars = [SELECT Id, Name, Model__c, Color__c, Price__c, Showroom__r.Name, Car_Owner__r.Name
	// 	FROM Car__c];
	// 	System.debug('>>>>>>>>>>>>>>>> Single car:' + getAllCars);
	// }

	public PageReference save() {
		return null;
	}

	// public PageReference save() {
	// 	PageReference pageReference = null;

	// 	errorMessage = '';
	// 	error = false;
	// 	Contact ld = (Contact) stdCtrl.getRecord();
	// 	if ((String.isEmpty(ld.Email)) || (String.isEmpty(ld.Password__c))) {
	// 		errorMessage = 'Please enter all required fields';
	// 		error = true;
	// 	} else {
	// 		try {
	// 			insert ld;
	// 			pageReference = Page.HomePage;
	// 			pageReference.getParameters().put('id', ld.id);
	// 			pageReference.setRedirect(true);
	// 		} catch (Exception e) {
	// 			errorMessage = 'An error has occurred: ' + e.getMessage();
	// 			error = true;
	// 		}
	// 	}
	// 	return pageReference;
	// }
}